# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:50:37+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import (
    CreatorRolesGetResponse,
    CreatorsGetResponse,
    DevelopersGetResponse,
    DeveloperSingle,
    GamesGamePkAdditionsGetResponse,
    GamesGamePkDevelopmentTeamGetResponse,
    GamesGamePkGameSeriesGetResponse,
    GamesGamePkParentGamesGetResponse,
    GamesGamePkScreenshotsGetResponse,
    GamesGamePkStoresGetResponse,
    GamesGetResponse,
    GameSingle,
    GenresGetResponse,
    GenreSingle,
    Movie,
    ParentAchievement,
    PersonSingle,
    PlatformsGetResponse,
    PlatformSingle,
    PlatformsListsParentsGetResponse,
    PublishersGetResponse,
    PublisherSingle,
    Reddit,
    StoresGetResponse,
    StoreSingle,
    TagsGetResponse,
    TagSingle,
    Twitch,
    Youtube,
)

app = MCPProxy(
    contact={'x-twitter': 'rawgtheworld'},
    description="\nThe largest open video games database.\n\n### Why build on RAWG\n- More than 350,000 games for 50 platforms including mobiles.\n- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,\nMetacritic ratings.\n- Where to buy: links to digital distribution services\n- Similar games based on visual similarity.\n- Player activity data: Steam average playtime and RAWG player counts and ratings.\n- Actively developing and constantly getting better by user contribution and our algorithms.\n\n### Terms of Use\n- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active\nhyperlink from every page where the data of RAWG is used.\n- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000\npage views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for\ncommercial terms.\n- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy\nto say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,\nand we will talk it through.\n- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.\nIf you don’t provide it, we may ban your requests.\n\n__[Read more](https://rawg.io/apidocs)__.\n",
    title='RAWG Video Games Database API',
    version='v1.0',
    servers=[{'url': 'https://api.rawg.io/api'}],
)


@app.get('/creator-roles', tags=['creator_information'])
def creator_roles_list(page: Optional[int] = None, page_size: Optional[int] = None):
    """
    Get a list of creator positions (jobs).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/creators', tags=['creator_information', 'developer_information'])
def creators_list(page: Optional[int] = None, page_size: Optional[int] = None):
    """
    Get a list of game creators.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/creators/{id}', tags=['creator_information', 'developer_information'])
def creators_read(id: Union[str, int, int, int]):
    """
    Get details of the creator.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/developers', tags=['developer_information', 'creator_information'])
def developers_list(page: Optional[int] = None, page_size: Optional[int] = None):
    """
    Get a list of game developers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/developers/{id}', tags=['creator_information', 'developer_information'])
def developers_read(id: int):
    """
    Get details of the developer.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/games',
    tags=[
        'game_catalog',
        'developer_information',
        'publisher_information',
        'store_catalog',
        'genre_catalog',
    ],
)
def games_list(
    page: Optional[int] = None,
    page_size: Optional[int] = None,
    search: Optional[str] = None,
    search_precise: Optional[bool] = None,
    search_exact: Optional[bool] = None,
    parent_platforms: Optional[str] = None,
    platforms: Optional[str] = None,
    stores: Optional[str] = None,
    developers: Optional[str] = None,
    publishers: Optional[str] = None,
    genres: Optional[str] = None,
    tags: Optional[str] = None,
    creators: Optional[str] = None,
    dates: Optional[str] = None,
    updated: Optional[str] = None,
    platforms_count: Optional[int] = None,
    metacritic: Optional[str] = None,
    exclude_collection: Optional[int] = None,
    exclude_additions: Optional[bool] = None,
    exclude_parents: Optional[bool] = None,
    exclude_game_series: Optional[bool] = None,
    exclude_stores: Optional[str] = None,
    ordering: Optional[str] = None,
):
    """
    Get a list of games.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{game_pk}/additions', tags=['game_catalog'])
def games_additions_list(
    page: Optional[int] = None, page_size: Optional[int] = None, game_pk: str = ...
):
    """
    Get a list of DLC's for the game, GOTY and other editions, companion apps, etc.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/games/{game_pk}/development-team',
    tags=['creator_information', 'developer_information'],
)
def games_development_team_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
    game_pk: str = ...,
):
    """
    Get a list of individual creators that were part of the development team.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{game_pk}/game-series', tags=['game_catalog'])
def games_game_series_list(
    page: Optional[int] = None, page_size: Optional[int] = None, game_pk: str = ...
):
    """
    Get a list of games that are part of the same series.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{game_pk}/parent-games', tags=['game_catalog'])
def games_parent_games_list(
    page: Optional[int] = None, page_size: Optional[int] = None, game_pk: str = ...
):
    """
    Get a list of parent games for DLC's and editions.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{game_pk}/screenshots', tags=['game_catalog', 'game_media'])
def games_screenshots_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
    game_pk: str = ...,
):
    """
    Get screenshots for the game.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{game_pk}/stores', tags=['store_catalog'])
def games_stores_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
    game_pk: str = ...,
):
    """
    Get links to the stores that sell the game.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}', tags=['game_catalog'])
def games_read(id: Union[str, int, int, int]):
    """
    Get details of the game.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}/achievements', tags=['game_catalog'])
def games_achievements_read(id: Union[str, int, int, int]):
    """
    Get a list of game achievements.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}/movies', tags=['game_media'])
def games_movies_read(id: Union[str, int, int, int]):
    """
    Get a list of game trailers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}/reddit', tags=['game_catalog'])
def games_reddit_read(id: Union[str, int, int, int]):
    """
    Get a list of most recent posts from the game's subreddit.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}/suggested', tags=['game_catalog'])
def games_suggested_read(id: Union[str, int, int, int]):
    """
    Get a list of visually similar games, available only for business and enterprise API users.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}/twitch', tags=['game_catalog', 'game_media'])
def games_twitch_read(id: Union[str, int, int, int]):
    """
    Get streams on Twitch associated with the game, available only for business and enterprise API users.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/games/{id}/youtube', tags=['game_media'])
def games_youtube_read(id: Union[str, int, int, int]):
    """
    Get videos from YouTube associated with the game, available only for business and enterprise API users.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/genres', tags=['genre_catalog'])
def genres_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
):
    """
    Get a list of video game genres.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/genres/{id}', tags=['genre_catalog'])
def genres_read(id: int):
    """
    Get details of the genre.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/platforms', tags=['platform_catalog'])
def platforms_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
):
    """
    Get a list of video game platforms.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/platforms/lists/parents',
    description=""" For instance, for PS2 and PS4 the “parent platform” is PlayStation. """,
    tags=['platform_catalog'],
)
def platforms_lists_parents_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
):
    """
    Get a list of parent platforms.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/platforms/{id}', tags=['platform_catalog'])
def platforms_read(id: int):
    """
    Get details of the platform.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/publishers', tags=['publisher_information'])
def publishers_list(page: Optional[int] = None, page_size: Optional[int] = None):
    """
    Get a list of video game publishers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/publishers/{id}', tags=['publisher_information', 'creator_information'])
def publishers_read(id: int):
    """
    Get details of the publisher.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/stores', tags=['store_catalog'])
def stores_list(
    ordering: Optional[str] = None,
    page: Optional[int] = None,
    page_size: Optional[int] = None,
):
    """
    Get a list of video game storefronts.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/stores/{id}', tags=['store_catalog'])
def stores_read(id: int):
    """
    Get details of the store.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/tags', tags=['tag_information'])
def tags_list(page: Optional[int] = None, page_size: Optional[int] = None):
    """
    Get a list of tags.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/tags/{id}', tags=['tag_information'])
def tags_read(id: int):
    """
    Get details of the tag.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
