# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:50:37+00:00

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, conint, constr


class Developer(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class DeveloperSingle(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class Name(Enum):
    Everyone = 'Everyone'
    Everyone_10_ = 'Everyone 10+'
    Teen = 'Teen'
    Mature = 'Mature'
    Adults_Only = 'Adults Only'
    Rating_Pending = 'Rating Pending'


class Slug(Enum):
    everyone = 'everyone'
    everyone_10_plus = 'everyone-10-plus'
    teen = 'teen'
    mature = 'mature'
    adults_only = 'adults-only'
    rating_pending = 'rating-pending'


class EsrbRating(BaseModel):
    id: Optional[int] = None
    name: Optional[Name] = None
    slug: Optional[Slug] = None


class Platform1(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None


class Requirements(BaseModel):
    minimum: Optional[str] = None
    recommended: Optional[str] = None


class Platform(BaseModel):
    platform: Optional[Platform1] = None
    released_at: Optional[str] = None
    requirements: Optional[Requirements] = None


class Game(BaseModel):
    added: Optional[int] = Field(None, title='Added')
    added_by_status: Optional[Dict[str, Any]] = Field(None, title='Added by status')
    background_image: Optional[AnyUrl] = Field(None, title='Background image')
    esrb_rating: Optional[EsrbRating] = None
    id: Optional[int] = Field(None, title='ID')
    metacritic: Optional[int] = Field(None, title='Metacritic')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    platforms: Optional[List[Platform]] = None
    playtime: Optional[int] = Field(None, description='in hours', title='Playtime')
    rating: float = Field(..., title='Rating')
    rating_top: Optional[int] = Field(None, title='Rating top')
    ratings: Optional[Dict[str, Any]] = Field(None, title='Ratings')
    ratings_count: Optional[int] = Field(None, title='Ratings count')
    released: Optional[date] = Field(None, title='Released')
    reviews_text_count: Optional[str] = Field(None, title='Reviews text count')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )
    suggestions_count: Optional[int] = Field(None, title='Suggestions count')
    tba: Optional[bool] = Field(None, title='TBA')
    updated: Optional[datetime] = Field(None, title='Updated')


class GamePersonList(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class GamePlatformMetacritic(BaseModel):
    metascore: Optional[int] = Field(None, title='Metascore')
    url: Optional[constr(min_length=1)] = Field(None, title='Url')


class EsrbRating1(BaseModel):
    id: Optional[int] = None
    name: Optional[Name] = None
    slug: Optional[Slug] = None


class Platform3(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None


class Platform2(BaseModel):
    platform: Optional[Platform3] = None
    released_at: Optional[str] = None
    requirements: Optional[Requirements] = None


class GameSingle(BaseModel):
    achievements_count: Optional[int] = Field(None, title='Achievements count')
    added: Optional[int] = Field(None, title='Added')
    added_by_status: Optional[Dict[str, Any]] = Field(None, title='Added by status')
    additions_count: Optional[int] = Field(None, title='Additions count')
    alternative_names: Optional[List[constr(min_length=1, max_length=200)]] = None
    background_image: Optional[AnyUrl] = Field(None, title='Background image')
    background_image_additional: Optional[str] = Field(
        None, title='Background image additional'
    )
    creators_count: Optional[int] = Field(None, title='Creators count')
    description: Optional[constr(min_length=1)] = Field(None, title='Description')
    esrb_rating: Optional[EsrbRating1] = None
    game_series_count: Optional[int] = Field(None, title='Game series count')
    id: Optional[int] = Field(None, title='ID')
    metacritic: Optional[int] = Field(None, title='Metacritic')
    metacritic_platforms: Optional[List[GamePlatformMetacritic]] = None
    metacritic_url: Optional[constr(min_length=1)] = Field(
        None,
        description='For example "http://www.metacritic.com/game/playstation-4/the-witcher-3-wild-hunt"',
        title='Metacritic url',
    )
    movies_count: Optional[int] = Field(None, title='Movies count')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    name_original: Optional[constr(min_length=1)] = Field(None, title='Name original')
    parent_achievements_count: Optional[str] = Field(
        None, title='Parent achievements count'
    )
    parents_count: Optional[int] = Field(None, title='Parents count')
    platforms: Optional[List[Platform2]] = None
    playtime: Optional[int] = Field(None, description='in hours', title='Playtime')
    rating: float = Field(..., title='Rating')
    rating_top: Optional[int] = Field(None, title='Rating top')
    ratings: Optional[Dict[str, Any]] = Field(None, title='Ratings')
    ratings_count: Optional[int] = Field(None, title='Ratings count')
    reactions: Optional[Dict[str, Any]] = Field(None, title='Reactions')
    reddit_count: Optional[int] = Field(None, title='Reddit count')
    reddit_description: Optional[constr(min_length=1)] = Field(
        None, title='Reddit description'
    )
    reddit_logo: Optional[AnyUrl] = Field(None, title='Reddit logo')
    reddit_name: Optional[constr(min_length=1)] = Field(None, title='Reddit name')
    reddit_url: Optional[constr(min_length=1)] = Field(
        None,
        description='For example "https://www.reddit.com/r/uncharted/" or "uncharted"',
        title='Reddit url',
    )
    released: Optional[date] = Field(None, title='Released')
    reviews_text_count: Optional[str] = Field(None, title='Reviews text count')
    screenshots_count: Optional[int] = Field(None, title='Screenshots count')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )
    suggestions_count: Optional[int] = Field(None, title='Suggestions count')
    tba: Optional[bool] = Field(None, title='TBA')
    twitch_count: Optional[str] = Field(None, title='Twitch count')
    updated: Optional[datetime] = Field(None, title='Updated')
    website: Optional[AnyUrl] = Field(None, title='Website')
    youtube_count: Optional[str] = Field(None, title='Youtube count')


class GameStoreFull(BaseModel):
    game_id: Optional[str] = Field(None, title='Game id')
    id: Optional[int] = Field(None, title='ID')
    store_id: Optional[str] = Field(None, title='Store id')
    url: AnyUrl = Field(..., title='Url')


class Genre(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class GenreSingle(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class Movie(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, title='Data')
    id: Optional[int] = Field(None, title='ID')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    preview: Optional[AnyUrl] = Field(None, title='Preview')


class ParentAchievement(BaseModel):
    description: Optional[constr(min_length=1)] = Field(None, title='Description')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    percent: Optional[Decimal] = Field(None, title='Percent')


class Person(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class PersonSingle(BaseModel):
    description: Optional[constr(min_length=1)] = Field(None, title='Description')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1) = Field(..., title='Name')
    rating: Optional[Decimal] = Field(None, title='Rating')
    rating_top: Optional[int] = Field(None, title='Rating top')
    reviews_count: Optional[int] = Field(None, title='Reviews count')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )
    updated: Optional[datetime] = Field(None, title='Updated')


class Platform4(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )
    year_end: Optional[conint(ge=0, le=32767)] = Field(None, title='Year end')
    year_start: Optional[conint(ge=0, le=32767)] = Field(None, title='Year start')


class PlatformParentSingle(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    platforms: List[Platform4]
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class PlatformSingle(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )
    year_end: Optional[conint(ge=0, le=32767)] = Field(None, title='Year end')
    year_start: Optional[conint(ge=0, le=32767)] = Field(None, title='Year start')


class Position(BaseModel):
    id: Optional[int] = Field(None, title='ID')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class Publisher(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class PublisherSingle(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class Reddit(BaseModel):
    created: Optional[datetime] = Field(None, title='Created')
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(None, title='Image')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    text: Optional[constr(min_length=1)] = Field(None, title='Text')
    url: Optional[AnyUrl] = Field(None, title='Url')
    username: Optional[constr(min_length=1)] = Field(None, title='Username')
    username_url: Optional[AnyUrl] = Field(None, title='Username url')


class ScreenShot(BaseModel):
    height: Optional[int] = Field(None, title='Height')
    hidden: Optional[bool] = Field(
        False, description='Set image as hidden or visible.', title='Hidden'
    )
    id: Optional[int] = Field(None, title='ID')
    image: Optional[AnyUrl] = Field(
        None, description='An image file with size up to 20 MB.', title='Image'
    )
    width: Optional[int] = Field(None, title='Width')


class Store(BaseModel):
    domain: Optional[constr(max_length=255)] = Field(None, title='Domain')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class StoreSingle(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    domain: Optional[constr(max_length=255)] = Field(None, title='Domain')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class Tag(BaseModel):
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    language: Optional[constr(min_length=1)] = Field(None, title='Language')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class TagSingle(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    games_count: Optional[int] = Field(None, title='Games count')
    id: Optional[int] = Field(None, title='ID')
    image_background: Optional[AnyUrl] = Field(None, title='Image background')
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    slug: Optional[constr(pattern=r'^[-a-zA-Z0-9_]+$', min_length=1)] = Field(
        None, title='Slug'
    )


class Twitch(BaseModel):
    created: Optional[datetime] = Field(None, title='Created')
    description: Optional[constr(min_length=1)] = Field(None, title='Description')
    external_id: Optional[int] = Field(None, title='External id')
    id: Optional[int] = Field(None, title='ID')
    language: Optional[constr(min_length=1)] = Field(None, title='Language')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    published: Optional[datetime] = Field(None, title='Published')
    thumbnail: Optional[AnyUrl] = Field(None, title='Thumbnail')
    view_count: Optional[int] = Field(None, title='View count')


class Youtube(BaseModel):
    channel_id: Optional[constr(min_length=1)] = Field(None, title='Channel id')
    channel_title: Optional[constr(min_length=1)] = Field(None, title='Channel title')
    comments_count: Optional[int] = Field(None, title='Comments count')
    created: Optional[datetime] = Field(None, title='Created')
    description: Optional[constr(min_length=1)] = Field(None, title='Description')
    dislike_count: Optional[int] = Field(None, title='Dislike count')
    external_id: Optional[constr(min_length=1)] = Field(None, title='External id')
    favorite_count: Optional[int] = Field(None, title='Favorite count')
    id: Optional[int] = Field(None, title='ID')
    like_count: Optional[int] = Field(None, title='Like count')
    name: Optional[constr(min_length=1)] = Field(None, title='Name')
    thumbnails: Optional[Dict[str, Any]] = Field(None, title='Thumbnails')
    view_count: Optional[int] = Field(None, title='View count')


class CreatorRolesGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Position]


class CreatorsGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Person]


class DevelopersGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Developer]


class GamesGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Game]


class GamesGamePkAdditionsGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Game]


class GamesGamePkDevelopmentTeamGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[GamePersonList]


class GamesGamePkGameSeriesGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Game]


class GamesGamePkParentGamesGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Game]


class GamesGamePkScreenshotsGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[ScreenShot]


class GamesGamePkStoresGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[GameStoreFull]


class GenresGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Genre]


class PlatformsGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Platform4]


class PlatformsListsParentsGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[PlatformParentSingle]


class PublishersGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Publisher]


class StoresGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Store]


class TagsGetResponse(BaseModel):
    count: int
    next: Optional[AnyUrl] = None
    previous: Optional[AnyUrl] = None
    results: List[Tag]
